transformation:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: airflow
      pass: airflow
      dbname: airflow
      schema: public
  target: dev
